(in-package :jgart.compose)

(defun read-lines (filepath-name)
  (let (lines)
    (with-open-file (stream filepath-name)
      (do ((line (read-line stream nil) (read-line stream nil)))
          ((null line))
        (push line lines)))
    (nreverse lines)))

(defun read-tone-rows (filepath-name)
  (let ((result '()))
    (let ((rows (read-lines filepath-name)))
      (dolist (row rows)
        (push (split-string row) result)))
    (nreverse result)))

(defun universe-helper (l)
  (remove-if
   (lambda (s) (string= "_" s)) l))

(defun parse-tone-rows (filepath-name)
  (print "i am here")
  (let ((tone-rows (read-tone-rows filepath-name)))
    (dolist (tone-row tone-rows)
      (when (/= (length *universe*) (length tone-row))
        (error "You supplied ~a notes in on line TODO but only 12 are allowed per line."
               (length tone-row)))
      (let ((row (make-list (length *universe*) :initial-element nil))
            (index 0))
        (let ((universe (comp (mapcar #'parse-note (universe-helper tone-row)))))
          (dolist (note tone-row)
            (unless (>= index (length *universe*))
            (when (equal note "_")
                (setf (elt row index) (pop universe))
                (setf (elt row index) (parse-note note)))
            (incf index))))
      row))))
